version: '3.8'

services:
  # Business 5: S3 Storage (MinIO)
  minio:
    image: minio/minio
    container_name: s3_storage
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - /mnt/hdd_storage/minio:/data  # Map to your large HDD ZFS pool
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console

volumes:
  minio_data:
